receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/jaeger:
    endpoint: http://jaeger:43017
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
