logs: []
services:
  - name: checkout
    methods:
      - name: process
        stdout: Processing Order
        sleep_ms: 1000
  - name: payments
    methods:
      - name: charge
        stdout: Charging amount
        calls:
          - name: checkout
            method: process
        sleep_ms: 1000
    invoke:
      - charge
