logs: []
services:
  - name: checkout
    methods:
      - name: process
        stdout: Processing Order
        sleep_ms: 100
  - name: user_service
    methods:
      - name: get_user
        stdout: Getting user
        sleep_ms: 100
  - name: product_service
    methods:
      - name: get_product
        stdout: Getting product
        sleep_ms: 100
  - name: web_frontend
    methods:
      - name: start_checkout
        stdout: Starting checkout
        calls:
          - name: product_service
            method: get_product
          - name: user_service
            method: get_user
          - name: checkout
            method: process
        sleep_ms: 100
    invoke:
      - start_checkout
